export const DELIVERY_STATE = {
    PLANNING : 'PLANNING',
    DISPATCHED : 'DISPATCHED',
    DELIVERED : 'DELIVERED',
    SUCCESS : 'SUCCESS',
    CLEAR : 'CLEAR',
    UNDEFINED : 'UNDEFINED',
};

export const DELIVERY_START_LOCATION_KEY = {
    LOCATION_A: 'LOCATION_A',
    LOCATION_B: 'LOCATION_B',
    LOCATION_C: 'LOCATION_C',
};

export const DELIVERY_START_LOCATION = {
    LOCATION_A: [40.71278, -74.0060],
    LOCATION_B: [40.72278, -74.0060],
    LOCATION_C: [40.73278, -74.0060],
};